### ISSUE TITLE
貌似缺少了lv3

### ISSUE THREAD

**Issue by kofing1** [28598519a/Aeon_AssetDecDL#4]

**Comment by kofing1** [comment]
[yb.zip](https://github.com/28598519a/Aeon_AssetDecDL/files/12679784/yb.zip)
以上来自转序的lv3样本，我并没有解锁lv3的账号，所以想问一下有没有发现相关的线索

**Comment by cghhj1028** [comment]
而且还需要文件地址的assetlist吧

**Comment by boomberman20082009** [comment]
新的asset表似乎被加密了
明文的资产表LV1以及一些基础文件
[https://drive.google.com/file/d/1NoY1LJvdH3S1YNVsS0OSleiLv4QnnO5s/view?usp=sharing](url)
[https://drive.google.com/file/d/1te8aXpGK3eE6GJLuxGo1DEbAWJi6vtiZ/view?usp=sharing](url)

**Comment by boomberman20082009** [comment]
抓包只抓到lastest这个list，只包含LV1的文件
如果是动态下载，那就没戏了
