### ISSUE TITLE
地址更新

### ISSUE THREAD

**Issue by cui-yang** [28598519a/Aeon_AssetDecDL#8]
新地址如下
DownLoadFile("https://rp-cn-prod-server.rpfans.net/api/game-data/hash/latest?platform=android", Path.Combine(al, "assets.json"), true),
DownLoadFile("https://rp-cn-prod-server.rpfans.net/api/game-data/hash/request/latest?platform=android", Path.Combine(al, "assets_secret.json"), true)

**Comment by whatcanisaid** [comment]
想问问，该如何使用呢，我是小白，我只发现“Aeon_AssetDecDL-main”文件里的“MainWindow.xaml.cs”有这段，我把这段替换之后，如何把“Aeon_AssetDecDL-main”转化为可用程序呢，我可以有偿
